// <auto-generated />
using System;
using CobrosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CobrosApi.Migrations
{
    [DbContext(typeof(CobrosDbContext))]
    [Migration("20260521183703_AddCuotaYAplicacion")]
    partial class AddCuotaYAplicacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CobrosApi.Models.AplicacionCuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuotaId")
                        .HasColumnType("integer");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorAplicado")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuotaId");

                    b.HasIndex("PagoId");

                    b.ToTable("AplicacionesCuota");
                });

            modelBuilder.Entity("CobrosApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CuentaBancaria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Llave")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ZonaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Juanito",
                            Direccion = "Calle Principal #123, Centro",
                            Estado = "activo",
                            Identificacion = "12345678",
                            Nombre = "Juan Pérez García",
                            Telefono = "555-0101",
                            ZonaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Alias = "Mary",
                            Direccion = "Av. Norte #456",
                            Estado = "activo",
                            Identificacion = "87654321",
                            Nombre = "María López Ruiz",
                            Telefono = "555-0202",
                            ZonaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Barrio Sur #789",
                            Estado = "activo",
                            Identificacion = "11223344",
                            Nombre = "Carlos Martínez",
                            Telefono = "555-0303",
                            ZonaId = 3
                        },
                        new
                        {
                            Id = 4,
                            Direccion = "Calle 5 #12",
                            Estado = "activo",
                            Identificacion = "44332211",
                            Nombre = "Ana González Torres",
                            Telefono = "555-0404",
                            ZonaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Alias = "Pedrito",
                            Direccion = "Av. Central #321",
                            Estado = "inactivo",
                            Identificacion = "55667788",
                            Nombre = "Pedro Rodríguez",
                            Telefono = "555-0505",
                            ZonaId = 2
                        },
                        new
                        {
                            Id = 6,
                            Direccion = "Plaza Mayor #7",
                            Estado = "activo",
                            Identificacion = "99887766",
                            Nombre = "Sofía Ramírez",
                            Telefono = "555-0606",
                            ZonaId = 1
                        });
                });

            modelBuilder.Entity("CobrosApi.Models.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEsperada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("integer");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SaldoPagado")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorCuota")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoId");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("CobrosApi.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoId");

                    b.ToTable("Pagos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaPago = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrestamoId = 1,
                            Valor = 46154m
                        },
                        new
                        {
                            Id = 2,
                            FechaPago = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrestamoId = 1,
                            Valor = 46154m
                        },
                        new
                        {
                            Id = 3,
                            FechaPago = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrestamoId = 1,
                            Valor = 46154m
                        },
                        new
                        {
                            Id = 4,
                            FechaPago = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrestamoId = 2,
                            Valor = 50000m
                        },
                        new
                        {
                            Id = 5,
                            FechaPago = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrestamoId = 2,
                            Valor = 50000m
                        },
                        new
                        {
                            Id = 6,
                            FechaPago = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrestamoId = 3,
                            Valor = 150000m
                        },
                        new
                        {
                            Id = 7,
                            FechaPago = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrestamoId = 4,
                            Valor = 92308m
                        },
                        new
                        {
                            Id = 8,
                            FechaPago = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrestamoId = 4,
                            Valor = 92308m
                        });
                });

            modelBuilder.Entity("CobrosApi.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadCuotas")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrecuenciaPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("InteresProyectado")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorCuota")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorPrestado")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Prestamos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadCuotas = 26,
                            ClienteId = 1,
                            FechaFinal = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaPrestamo = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FrecuenciaPago = "semanal",
                            InteresProyectado = 200000m,
                            ValorCuota = 46154m,
                            ValorPrestado = 1000000m,
                            ValorTotal = 1200000m
                        },
                        new
                        {
                            Id = 2,
                            CantidadCuotas = 12,
                            ClienteId = 2,
                            FechaFinal = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaPrestamo = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FrecuenciaPago = "quincenal",
                            InteresProyectado = 100000m,
                            ValorCuota = 50000m,
                            ValorPrestado = 500000m,
                            ValorTotal = 600000m
                        },
                        new
                        {
                            Id = 3,
                            CantidadCuotas = 6,
                            ClienteId = 3,
                            FechaFinal = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaPrestamo = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FrecuenciaPago = "mensual",
                            InteresProyectado = 150000m,
                            ValorCuota = 150000m,
                            ValorPrestado = 750000m,
                            ValorTotal = 900000m
                        },
                        new
                        {
                            Id = 4,
                            CantidadCuotas = 26,
                            ClienteId = 4,
                            FechaFinal = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaPrestamo = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FrecuenciaPago = "semanal",
                            InteresProyectado = 400000m,
                            ValorCuota = 92308m,
                            ValorPrestado = 2000000m,
                            ValorTotal = 2400000m
                        },
                        new
                        {
                            Id = 5,
                            CantidadCuotas = 180,
                            ClienteId = 1,
                            FechaFinal = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaPrestamo = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FrecuenciaPago = "diario",
                            InteresProyectado = 60000m,
                            ValorCuota = 2000m,
                            ValorPrestado = 300000m,
                            ValorTotal = 360000m
                        },
                        new
                        {
                            Id = 6,
                            CantidadCuotas = 12,
                            ClienteId = 6,
                            FechaFinal = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaPrestamo = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FrecuenciaPago = "quincenal",
                            InteresProyectado = 300000m,
                            ValorCuota = 150000m,
                            ValorPrestado = 1500000m,
                            ValorTotal = 1800000m
                        });
                });

            modelBuilder.Entity("CobrosApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Autorizado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CobrosApi.Models.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Zonas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "activo",
                            Nombre = "Centro"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "activo",
                            Nombre = "Norte"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "inactivo",
                            Nombre = "Sur"
                        });
                });

            modelBuilder.Entity("CobrosApi.Models.AplicacionCuota", b =>
                {
                    b.HasOne("CobrosApi.Models.Cuota", "Cuota")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("CuotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CobrosApi.Models.Pago", "Pago")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuota");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("CobrosApi.Models.Cliente", b =>
                {
                    b.HasOne("CobrosApi.Models.Zona", "Zona")
                        .WithMany("Clientes")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("CobrosApi.Models.Cuota", b =>
                {
                    b.HasOne("CobrosApi.Models.Prestamo", "Prestamo")
                        .WithMany("Cuotas")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("CobrosApi.Models.Pago", b =>
                {
                    b.HasOne("CobrosApi.Models.Prestamo", "Prestamo")
                        .WithMany("Pagos")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("CobrosApi.Models.Prestamo", b =>
                {
                    b.HasOne("CobrosApi.Models.Cliente", "Cliente")
                        .WithMany("Prestamos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CobrosApi.Models.Cliente", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("CobrosApi.Models.Cuota", b =>
                {
                    b.Navigation("Aplicaciones");
                });

            modelBuilder.Entity("CobrosApi.Models.Pago", b =>
                {
                    b.Navigation("Aplicaciones");
                });

            modelBuilder.Entity("CobrosApi.Models.Prestamo", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("CobrosApi.Models.Zona", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
